language: python

python:
  - 2.7
  - 3.4

env:
  matrix:
  - DJANGO='django16' CMS='cms30'
  - DJANGO='django16' CMS='cms31'
  - DJANGO='django16' CMS='cms32'
  - DJANGO='django17' CMS='cms30'
  - DJANGO='django17' CMS='cms31'
  - DJANGO='django17' CMS='cms32'
  - DJANGO='django18' CMS='cms31'
  - DJANGO='django18' CMS='cms32'

matrix:
  allow_failures:
    - python: 2.7
      env: DJANGO='django16' CMS='cms30'
    - python: 2.7
      env: DJANGO='django16' CMS='cms31'
    - python: 2.7
      env: DJANGO='django16' CMS='cms32'
    - python: 2.7
      env: DJANGO='django17' CMS='cms30'
    - python: 2.7
      env: DJANGO='django18' CMS='cms31'
    - python: 2.7
      env: DJANGO='django18' CMS='cms32'
    - python: 3.4
      env: DJANGO='django18' CMS='cms31'
    - python: 3.4
      env: DJANGO='django18' CMS='cms32'

install:
  - pip install tox

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then export PYVER=py26; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export PYVER=py27; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then export PYVER=py33; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then export PYVER=py34; fi"

script:
  - tox -e"$PYVER-$DJANGO-$CMS"
