language: python

python:
  - 2.7
#  - 3.3

env:
  - DJANGO=1.6.8 MIGRATE='true'
  - DJANGO=1.7.1 MIGRATE='./manage.py migrate --settings=bs3demo.settings'

branches:
  only:
    - master

install:
  - pip install -q Django==$DJANGO
  - pip install -r examples/bs3demo/requirements.txt
  - python setup.py -q install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
 - cd examples && $MIGRATE && ./manage.py test bs3demo --settings=bs3demo.settings
