language: python

python:
  - 2.7
  - 3.4

env:
  matrix:
  - DJANGO='django18' CMS='cms31'
  - DJANGO='django18' CMS='cms32'
  - DJANGO='django19' CMS='cms32'

install:
  - pip install tox

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export PYVER=py27; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then export PYVER=py34; fi"

script:
  - tox -e"$PYVER-$DJANGO-$CMS"
