language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGOVER=django21 CMSVER=cms36
  - DJANGOVER=django22 CMSVER=cms36
  - DJANGOVER=django22 CMSVER=cms37
  - DJANGOVER=django30 CMSVER=cms37
  - DJANGOVER=django30 CMSVER=cms40

matrix:
  allow_failures:
    - python: 3.8
      env: DJANGOVER=django21 CMSVER=cms36
    - python: 3.8
      env: DJANGOVER=django22 CMSVER=cms36
    - python: 3.8
      env: DJANGOVER=django30 CMSVER=cms37
    - python: 3.8
      env: DJANGOVER=django30 CMSVER=cms40

install:
  - pip install tox

script:
  - export TOX_ENV=py${TRAVIS_PYTHON_VERSION/./}-${DJANGOVER}-${CMSVER}
  - tox -e "$TOX_ENV"
