language: python

python:
  - 2.7
  - 3.3

env:
  - DJANGO=1.5.8
  - DJANGO=1.6.5

branches:
  only:
    - master

matrix:
  exclude:
  - python: 3.3
    env: DJANGO=1.5.8

install:
  - pip install -q Django==$DJANGO
  - pip install -r requirements.txt
  - python setup.py -q install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
 - cd examples && ./manage.py test bootstrap3 --settings=bootstrap3.tests.settings
